sudo: required
services:
  - docker

before_install:
  - docker build -t adammarczyk/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run adammarczyk/react-test npm test -- --coverage

after_success:
  - docker build -t adammarczyk/multi-client ./client
  - docker build -t adammarczyk/multi-nginx ./nginx
  - docker build -t adammarczyk/multi-server ./server
  - docker build -t adammarczyk/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push adammarczyk/multi-client
  - docker push adammarczyk/multi-nginx
  - docker push adammarczyk/multi-server
  - docker push adammarczyk/multi-worker
